apiVersion: apps/v1
kind: ReplicaSet
metadata:
  # Unique key of the ReplicaSet instance
  name: nginx
spec:
  # 3 Pods should exist at all times.
  replicas: 1 # always one pod should run
  selector:
    matchLabels:
      app: nginx
  template: # pod template
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      # Run the nginx image
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80